### ISSUE TITLE
non-square resolution

### ISSUE THREAD

**Issue by gladwel** [itjustis/sdthings#2]
Can I make the video not quadratic? It gives an error 

RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 28 but got size 27 for tensor number 1 in the list.

**Comment by itjustis** [comment]
hi! my guess is you using resolution not a multiple of 64.  so try something like 512x768 or 768x960

i guess i should add an autoconversion of size to multiple of 64.

**Comment by gladwel** [comment]
Great, it works, thank you very much!
